# Дисциплина: КМСС

# Практика №5

### Задание

Напишите программы с использованием Python или C# для решения следующих задач.

In [1]:
import numpy as np

from CMoCSm.SoLE.solvers import GaussianEliminationSolver
from CMoCSm.SoLE.solvers import LeastSquaresSolver

#### Задача 1

Решить систему (1) линейных алгебраических уравнений методом Гаусса (схема единственного деления).

$$ \begin{equation} \left\{ \begin{array}{}{}{} 2x_1 + x_2 + 4x_3 = 16; &\\ 3x_1 + 2x_2 + x_3 = 10; &\\ x_1 + 3x_2 + 3x_3 = 16. \end{array} \right. (1) \end{equation} $$

##### Примечание

_Для решения этой задачи реализуем тот метод, который требуется использовать в следующей задачи. Ведь разница между ними в том, что настоящий метод подвержен `ZeroDevisionError`._

In [2]:
matrix_a = np.array(
    [
        [2, 1, 4],
        [3, 2, 1],
        [1, 3, 3]
    ]
)
matrix_b = np.array(
    [
        [16],
        [10],
        [16]
    ]
)

In [3]:
np.linalg.solve(matrix_a, matrix_b)

array([[1.],
       [2.],
       [3.]])

##### Альтернативное решение

In [4]:
ges = GaussianEliminationSolver()
ges.fit(matrix_a, matrix_b)
ges.solve(3)

array([[1.],
       [2.],
       [3.]])

#### Задача 

[Методом Гаусса с выбором ведущего элемента по столбцам](https://textbooks.math.gatech.edu/ila/row-reduction.html) решить систему (2).

$$ \begin{equation} \left\{ \begin{array}{}{}{} -3x_1 + 2,099x_2 + 6x_3 = 3,901; &\\ 10x_1 - 7x_2 + 0x_3 = 7; &\\ 5x_1 - x_2 + 5x_3 = 6. \end{array} \right. (2) \end{equation} $$

In [5]:
matrix_a = np.array(
    [
        [-3, 2.099, 6],
        [10, -7, 0],
        [5, -1, 5]
    ]
)
matrix_b = np.array(
    [
        [3.901],
        [7],
        [6]
    ]
)

In [6]:
np.linalg.solve(matrix_a, matrix_b)

array([[ 0.],
       [-1.],
       [ 1.]])

##### Альтернативное решение

In [7]:
ges = GaussianEliminationSolver()
ges.fit(matrix_a, matrix_b)
ges.solve(3)

array([[ 0.],
       [-1.],
       [ 1.]])

#### Задача 3

Решить систему уравнений (3) методом Гаусса единственного деления.

$$ \begin{equation} \left\{ \begin{array}{}{}{} x_1 - x_2 + x_3 - 4x_4 = -2; &\\ 8x_1 - x_2 - x_3 + 2x_4 = 11; &\\ x_1 + 6x_2 - 2x_3 - 2x_4 = 6. \end{array} \right. (3) \end{equation} $$

##### Примечание

_Намного проще реализовать [метод наименьших квадратов](https://textbooks.math.gatech.edu/ila/least-squares.html), который в своей основе имеет как раз метод исключения Гаусса с выбором ведущего элемента по столбцам. По этой причине воспользуемся методом наименьших квадратов._

In [8]:
matrix_a = np.array(
    [
        [1, -1, 1, 4],
        [8, -1, -1, 2],
        [1, 6, -2, -2]
    ]
)
matrix_b = np.array(
    [
        [-2],
        [11],
        [-7]
    ]
)

In [9]:
np.linalg.lstsq(matrix_a, matrix_b, rcond=None)

(array([[ 1.42946593],
        [-1.9038674 ],
        [-0.21804788],
        [-1.27882136]]),
 array([], dtype=float64),
 3,
 array([8.67440198, 7.07918966, 2.93935776]))

##### Альтернативное решение

In [10]:
lss = LeastSquaresSolver()
lss.fit(matrix_a, matrix_b)
lss.solve(8)

array([[ 1.4047619 ],
       [-1.92857143],
       [-0.33333333],
       [-1.25      ]])