# Дисциплина: КМСС
# Практика №6

### Задание

Напишите программы с использованием Python или C# для решения
следующих задач.

In [1]:
import numpy as np

from CMoCSm.SoLE.solvers import TridiagonalMatrixSolver

#### Задача 1

Дана система линейных алгебраических уравнений (1) с [трёхдиагональной матрицей](https://en.wikipedia.org/wiki/Tridiagonal_matrix) $(n = 4)$.

$$ \begin{equation} \left\{ \begin{array}{}{}{}{} 5x_1 + 3x_2 = 8; &\\ 3x_1 + 6x_2 + x_3 = 10; &\\ x_2 - 4x_3 + 2x_4 = 3; &\\ x_3 - 3x_4 = -2. \end{array} \right. (1) \end{equation} $$

Решить эту систему методом [прогонки](https://en.wikipedia.org/wiki/Tridiagonal_matrix_algorithm).

In [2]:
matrix_a = np.array(
    [
        [5, 3, 0, 0],
        [3, 6, 1, 0],
        [0, 1, 4, -2],
        [0, 0, 1, -3],
    ]
)
matrix_b = np.array(
    [
        [8],
        [10],
        [3],
        [-2],
    ]
)

In [3]:
tms = TridiagonalMatrixSolver()
tms.fit(matrix_a, matrix_b)
tms.solve(3)

array([[1.],
       [1.],
       [1.],
       [1.]])

#### Задача 2

Дана система линейных алгебраических уравнений (2) с трёхдиагональной
матрицей, решить систему методом прогонки.

$$ \begin{equation} \left\{ \begin{array}{}{}{}{} x_1 + x_2 = 5; &\\ 2x_1 - x_2 + x_3 = 3; &\\ x_2 - x_3 + x_4 = 3; &\\ x_3 - x_4 = 7. \end{array} \right. (2) \end{equation} $$

In [4]:
matrix_a = np.array(
    [
        [1, 2, 0, 0],
        [2, -1, 1, 0],
        [0, 1, -1, 1],
        [0, 0, 1, 1],
    ]
)
matrix_b = np.array(
    [
        [5],
        [3],
        [3],
        [7],
    ]
)

In [5]:
tms = TridiagonalMatrixSolver()
tms.fit(matrix_a, matrix_b)
tms.solve(3)

array([[1.],
       [2.],
       [3.],
       [4.]])

#### Задача 2

Решить методом прогонки систему уравнений (3).

$$ \begin{equation} \left\{ \begin{array}{}{}{}{} 2x_1 + x_2 = 4; &\\ 2x_1 + 3x_2 - x_3 = 9; &\\ x_2 - x_3 + 3x_4 = 12; &\\ x_3 - x_4 = -4. \end{array} \right. (3) \end{equation} $$

In [6]:
matrix_a = np.array(
    [
        [2, 1, 0, 0],
        [2, 3, -1, 0],
        [0, 1, -1, 3],
        [0, 0, 1, -1],
    ]
)
matrix_b = np.array(
    [
        [4],
        [9],
        [12],
        [-4],
    ]
)

In [7]:
tms = TridiagonalMatrixSolver()
tms.fit(matrix_a, matrix_b)
tms.solve(3)

array([[ 1.],
       [ 2.],
       [-1.],
       [ 3.]])